USE ARDMAIN 
GO
WITH CTE1 (GOREV,BOLUM,SEBEP,TARIH,ADET,M2,AY,AY_SIRALAMA)
AS(

SELECT DISTINCT  SYSADM.BW_AUFTR_POS.ID as GÖREV_NO,SYSADM.BW_AUFTR_POS.REKLA_ORT AS REKLEMASYON_BÖLÜMÜ,SYSADM.BW_AUFTR_POS.REKLA_GRUND AS REKLEMASYON_SEBEBÝ,
SYSADM.BW_AUFTR_KOPF.DATUM_ERF AS GÝRÝÞ_TARÝHÝ,SYSADM.BW_AUFTR_KOPF.SU_STUECK as Adet ,SYSADM.BW_AUFTR_KOPF.SU_QM_FAKT AS m2 ,
CASE WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=1 THEN 'OCAK'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=2 THEN 'ÞUBAT'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=3 THEN 'MART'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=4 THEN 'NÝSAN'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=5 THEN 'MAYIS'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=6 THEN 'HAZÝRAN'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=7 THEN 'TEMMUZ'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=8 THEN 'AÐUSTOS'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=9 THEN 'EYLÜL'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=10 THEN 'EKÝM'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=11 THEN 'KASIM'
																																	WHEN MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF)=12 THEN 'ARALIK'
																																	
																																	END   AS AY,
																																	MONTH(SYSADM.BW_AUFTR_KOPF.DATUM_ERF) AS AY_SIRALAMA
  
						 

FROM SYSADM.BW_AUFTR_POS 

 JOIN SYSADM.BW_AUFTR_KOPF ON SYSADM.BW_AUFTR_POS.ID=SYSADM.BW_AUFTR_KOPF.ID

WHERE REKLA_ORT <> '<K.y.>' AND DATUM_ERF >='2022-01-01'


)
SELECT BOLUM,SUM(ADET)AS ADET,SUM(M2)AS M2,AY AS AY  FROM CTE1

GROUP BY BOLUM,AY,AY_SIRALAMA

ORDER BY AY_SIRALAMA ASC
-- TOTAL QUANTITY AND SQUARE METER OF RECLAMTION WITH RESPECT TO REGARDING DEPARTMENTS OVER MONTH AFTER 2022



WITH CTE2 (GOREV,BOLUM,SEBEP,TARIH,ADET,M2)
AS(

SELECT DISTINCT  SYSADM.BW_AUFTR_POS.ID as GÖREV_NO,SYSADM.BW_AUFTR_POS.REKLA_ORT AS REKLEMASYON_BÖLÜMÜ,SYSADM.BW_AUFTR_POS.REKLA_GRUND AS REKLEMASYON_SEBEBÝ,
SYSADM.BW_AUFTR_KOPF.DATUM_ERF AS GÝRÝÞ_TARÝHÝ,SYSADM.BW_AUFTR_KOPF.SU_STUECK as Adet ,SYSADM.BW_AUFTR_KOPF.SU_QM_FAKT AS m2

FROM SYSADM.BW_AUFTR_POS 

 JOIN SYSADM.BW_AUFTR_KOPF ON SYSADM.BW_AUFTR_POS.ID=SYSADM.BW_AUFTR_KOPF.ID

WHERE REKLA_ORT <> '<K.y.>' AND DATUM_ERF >'2022-01-01' 


)
SELECT BOLUM,SUM(ADET)AS ADET,SUM(M2)AS M2 FROM CTE2
GROUP BY BOLUM

-- TOTAL QUANTITY AND SQUARE METER OF RECLAMTION WITH RESPECT TO REGARDING DEPARTMENTS OVER 2022 


SELECT DISTINCT  SYSADM.BW_AUFTR_POS.ID as GÖREV_NO,SYSADM.BW_AUFTR_POS.REKLA_ORT AS REKLEMASYON_BÖLÜMÜ,SYSADM.BW_AUFTR_POS.REKLA_GRUND AS REKLEMASYON_SEBEBÝ,
SYSADM.BW_AUFTR_KOPF.DATUM_ERF AS GÝRÝÞ_TARÝHÝ,SYSADM.BW_AUFTR_KOPF.SU_STUECK as Adet ,SYSADM.BW_AUFTR_KOPF.SU_QM_FAKT AS m2

FROM SYSADM.BW_AUFTR_POS 

 JOIN SYSADM.BW_AUFTR_KOPF ON SYSADM.BW_AUFTR_POS.ID=SYSADM.BW_AUFTR_KOPF.ID

WHERE REKLA_ORT <> '<K.y.>' AND DATUM_ERF >'2022-01-01' 

-- DETAILED TABLE FOR RECLAMATION REASONS AND DEPARTMENT WITH RESPECT TO DATE



SELECT DISTINCT   SYSADM.BW_AUFTR_POS.ID as GÖREV_NO,AH_NAME1+AH_NAME2 AS MUSTERI
FROM SYSADM.BW_AUFTR_POS 

 JOIN SYSADM.BW_AUFTR_KOPF ON SYSADM.BW_AUFTR_POS.ID=SYSADM.BW_AUFTR_KOPF.ID

WHERE REKLA_ORT <> '<K.y.>' AND DATUM_ERF >'2022-01-01' 
ORDER BY 1 

-- TABLE FOR ID NUMBER TO CUSTOMER NAME