SELECT	GÖREV_NO as Order_Number,
		REKLEMASYON_BÖLÜMÜ as Departmant,
		REKLEMASYON_SEBEBİ as Reason,
		GİRİŞ_TARİHİ as Entry_Date,
		cast(Adet as int) as Quantity,
		m2 as Sqm,
		ORJ_GÖREV_NO as Referance_Order_Number,
		KOMB as Combination

FROM 
(
		SELECT 				POS.ID as GÖREV_NO,
							POS.REKLA_ORT AS REKLEMASYON_BÖLÜMÜ,
							POS.REKLA_GRUND AS REKLEMASYON_SEBEBİ,
							KOPF.DATUM_ERF  AS GİRİŞ_TARİHİ,
							KOPF.SU_STUECK as Adet ,
							KOPF.SU_QM_FAKT AS m2 ,
							POS.AUFTR_REF AS ORJ_GÖREV_NO,
							POS.PROD_BEZ1+POS.PROD_BEZ2 AS KOMB,
							ROW_NUMBER() OVER (PARTITION BY POS.ID ORDER BY POS.ID ) AS RN
		FROM SYSADM.BW_AUFTR_POS AS POS
	JOIN SYSADM.BW_AUFTR_KOPF AS KOPF ON POS.ID=KOPF.ID
	WHERE	
			REKLA_ORT <> '<K.y.>' 
		AND
			REKLA_GRUND <> '<K.y.>'


) AS Q1
WHERE RN=1

ORDER BY 4 DESC


-- TOTAL QUANTITY AND SQUARE METER OF RECLAMTION WITH RESPECT TO REGARDING DEPARTMENTS 


SELECT DISTINCT  SYSADM.BW_AUFTR_POS.ID as GÖREV_NO,SYSADM.BW_AUFTR_POS.REKLA_ORT AS REKLEMASYON_BÖLÜMÜ,SYSADM.BW_AUFTR_POS.REKLA_GRUND AS REKLEMASYON_SEBEBÝ,
SYSADM.BW_AUFTR_KOPF.DATUM_ERF AS GÝRÝÞ_TARÝHÝ,SYSADM.BW_AUFTR_KOPF.SU_STUECK as Adet ,SYSADM.BW_AUFTR_KOPF.SU_QM_FAKT AS m2

FROM SYSADM.BW_AUFTR_POS 

 JOIN SYSADM.BW_AUFTR_KOPF ON SYSADM.BW_AUFTR_POS.ID=SYSADM.BW_AUFTR_KOPF.ID

WHERE REKLA_ORT <> '<K.y.>' AND DATUM_ERF >'2022-01-01' 

-- DETAILED TABLE FOR RECLAMATION REASONS AND DEPARTMENT WITH RESPECT TO DATE



SELECT DISTINCT   SYSADM.BW_AUFTR_POS.ID as GÖREV_NO,AH_NAME1+AH_NAME2 AS MUSTERI
FROM SYSADM.BW_AUFTR_POS 

 JOIN SYSADM.BW_AUFTR_KOPF ON SYSADM.BW_AUFTR_POS.ID=SYSADM.BW_AUFTR_KOPF.ID

WHERE REKLA_ORT <> '<K.y.>' AND DATUM_ERF >'2022-01-01' 
ORDER BY 1 

-- TABLE FOR ID NUMBER TO CUSTOMER NAME
